name: 'yarn-install'
description: "yarn install"
outputs:
  random-number:
    description: 'Random number'
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        registry-url: 'https://registry.npmjs.org'
        node-version: 20.x
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run:  echo "yarn_cache_path=$(yarn config get cacheFolder)" >> "$GITHUB_OUTPUT"
    - name: Restore yarn cache
      uses: actions/cache@v4
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.yarn_cache_path }}
        key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
        restore-keys: |
          yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
