name: Pull Request
on:
  pull_request:
    branches: [ master, main ]

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Yarn install
  #       uses: ./.github/actions/yarn-install
  #     - name: Lint
  #       run: yarn lint

  test:
   # needs: ['lint']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Yarn install
        uses: ./.github/actions/yarn-install
      - name: test
        run: yarn test